
INSERT INTO public.products (slug, name, description, long_description, price, category, inventory_tag, image_day, image_night, dimensions, material, featured) VALUES
-- 5-inch lamps
('lamp-5in-1', '5-Inch Hanging Lamp — Style 1', 'Premium 5-inch handmade leather lampshade blending traditional artistry with modern elegance.', 'Handcrafted with genuine leather, this 5-inch lampshade blends traditional artistry with modern elegance. Perfect for luxury interiors, gifting, and décor lovers who value authenticity and craftsmanship. The intricate perforations cast beautiful shadow patterns when illuminated, transforming any corner into an ambient space.', 800, 'hanging-lamps', 'in-stock', '/images/products/lamp-5in-1.jpg', '/images/products/lamp-5in-1-night.jpg', '5" diameter', 'Genuine Leather, Brass Frame, Natural Dyes', false),
('lamp-5in-2', '5-Inch Hanging Lamp — Style 2', 'Compact handcrafted leather lamp with delicate folk-art perforations for intimate lighting.', 'This compact 5-inch leather hanging lamp features delicate folk-art perforations that create an intimate lighting ambiance. Hand-painted with natural camel drawing inks, the lamp showcases traditional Indian motifs in vibrant colors. Perfect for bedside tables, small corners, or as a decorative gift piece.', 800, 'hanging-lamps', 'in-stock', '/images/products/lamp-5in-2.jpg', '/images/products/lamp-5in-2-night.jpg', '5" diameter', 'Genuine Leather, Brass Frame, Natural Dyes', false),
-- 8-inch round lamps
('lamp-8in-round-1', '8-Inch Round Lamp — Style 1', 'Beautifully crafted 8-inch round leather lamp with intricate traditional motifs.', 'This handcrafted 8-inch round leather hanging lamp features intricate traditional Indian motifs. The carefully placed perforations cast mesmerizing shadow patterns across walls and ceilings when illuminated. Hand-painted with natural camel drawing inks on genuine leather, ensuring rich colors and long-lasting beauty.', 1300, 'hanging-lamps', 'in-stock', '/images/products/lamp-8in-1.jpg', '/images/products/lamp-8in-1-night.jpg', '8" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
('lamp-8in-round-2', '8-Inch Round Lamp — Style 2', 'Elegant 8-inch round lamp with vibrant folk-art patterns and warm ambient lighting.', 'This elegant 8-inch round leather lamp showcases vibrant folk-art patterns inspired by the Tholu Bommalata tradition. When illuminated, it creates a warm, inviting ambiance with intricate shadow play. Each lamp is meticulously hand-painted and perforated, making every piece unique.', 1300, 'hanging-lamps', 'in-stock', '/images/products/lamp-8in-2.jpg', '/images/products/lamp-8in-2-night.jpg', '8" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
-- 12-inch round lamps
('lamp-12in-round-1', '12-Inch Round Lamp — Style 1', 'Stunning 12-inch round leather lamp with detailed folk-art perforations.', 'This stunning 12-inch round leather hanging lamp transforms any room into a shadow theater. The leather is perforated in traditional folk-art patterns that cast mesmerizing shadows across walls and ceilings. By day, it is an elegant decorative piece; by night, it becomes a living art installation. Hand-painted with natural camel drawing inks on genuine leather.', 2500, 'hanging-lamps', 'in-stock', '/images/products/lamp-12in-round-1.jpg', '/images/products/lamp-12in-round-1-night.jpg', '12" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', true),
('lamp-12in-round-2', '12-Inch Round Lamp — Style 2', 'Heritage 12-inch round lamp with elaborate mythological motifs.', 'This heritage 12-inch round leather lamp features elaborate mythological motifs from Indian epics. The intricate perforations create a breathtaking play of light and shadow, transforming any space into an ambient sanctuary. Each lamp is entirely hand-painted and hand-perforated, ensuring museum-quality craftsmanship.', 2500, 'hanging-lamps', 'in-stock', '/images/products/lamp-12in-round-2.jpg', '/images/products/lamp-12in-round-2-night.jpg', '12" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
-- 12-inch square lamps
('lamp-12in-sq-1', '12-Inch Square Lamp — Style 1', 'Distinctive square leather lamp with geometric folk-art patterns.', 'This distinctive 12-inch square leather hanging lamp features a unique geometric silhouette combined with traditional folk-art patterns. The square form factor creates a contemporary aesthetic while the hand-painted leather and intricate perforations maintain authentic heritage craftsmanship. Perfect for modern interiors seeking a touch of tradition.', 2800, 'hanging-lamps', 'in-stock', '/images/products/lamp-12in-sq-1.jpg', '/images/products/lamp-12in-sq-1-night.jpg', '12" × 12" (Square)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
('lamp-12in-sq-2', '12-Inch Square Lamp — Style 2', 'Contemporary square lamp blending modern geometry with traditional leather artistry.', 'This contemporary 12-inch square leather lamp blends modern geometry with centuries-old leather artistry. The square panels feature hand-painted scenes from Indian mythology, and when illuminated, the perforations project stunning shadow patterns. A perfect fusion of heritage and modern design sensibility.', 2800, 'hanging-lamps', 'in-stock', '/images/products/lamp-12in-sq-2.jpg', '/images/products/lamp-12in-sq-2-night.jpg', '12" × 12" (Square)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
-- 16-inch round lamps
('lamp-16in-round-1', '16-Inch Round Lamp — Style 1', 'Grand 16-inch round leather lamp creating dramatic shadow art across entire rooms.', 'This grand 16-inch round leather hanging lamp creates dramatic shadow art across entire rooms. The larger surface area allows for more detailed and elaborate folk-art patterns, resulting in spectacular light and shadow displays. Hand-painted with natural camel drawing inks on premium genuine leather, this statement piece commands attention in any space.', 4500, 'hanging-lamps', 'made-to-order', '/images/products/lamp-16in-1.jpg', '/images/products/lamp-16in-1-night.jpg', '16" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', true),
('lamp-16in-round-2', '16-Inch Round Lamp — Style 2', 'Majestic 16-inch lamp with epic mythological scenes and rich detailing.', 'This majestic 16-inch round leather lamp features epic mythological scenes rendered in rich traditional colors. The generous size allows for extraordinary detail in both the painted artwork and the perforated patterns. When lit, it transforms your space into an immersive shadow theater experience.', 4500, 'hanging-lamps', 'made-to-order', '/images/products/lamp-16in-2.jpg', '/images/products/lamp-16in-2-night.jpg', '16" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', false),
-- 25-inch round lamps
('lamp-25in-round-1', '25-Inch Round Lamp — Style 1', 'Monumental 25-inch leather lamp — a museum-quality centerpiece of shadow art.', 'This monumental 25-inch round leather hanging lamp is a museum-quality centerpiece of shadow art. The expansive canvas allows for the most intricate and detailed folk-art compositions, featuring complete mythological narratives in a single piece. When illuminated, it fills entire rooms with breathtaking shadow patterns that dance across walls and ceilings. A true collector-grade artwork.', 8000, 'hanging-lamps', 'made-to-order', '/images/products/lamp-25in-1.jpg', '/images/products/lamp-25in-1-night.jpg', '25" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', true),
('lamp-25in-round-2', '25-Inch Round Lamp — Style 2', 'Spectacular 25-inch lamp with panoramic mythological scenes for grand spaces.', 'This spectacular 25-inch round leather lamp features panoramic mythological scenes spanning the entire surface. The largest in our collection, it serves as a stunning focal point for grand living rooms, lobbies, and heritage spaces. Hand-painted with natural camel drawing inks, every detail is meticulously crafted for lasting beauty.', 8000, 'hanging-lamps', 'made-to-order', '/images/products/lamp-25in-2.jpg', '/images/products/lamp-25in-2-night.jpg', '25" diameter (Round)', 'Genuine Leather, Brass Frame, Natural Dyes', false);
